import React, { createContext, useContext, useState } from 'react';

export type Language = 'th' | 'en' | 'ru';

export const translations = {
  th: {
    // Header
    consoleTitle: 'ระบบจองห้องประชุม',
    subtitle: 'สำนักงานใหญ่ Villa Carte Group • ชั้น 1 & 2',
    bookingModalSubtitle: 'ระบบจองห้องประชุม HQ • Villa Carte Group',
    ssoSubtitle: 'Villa Carte Group ระบบเข้าสู่ระบบรวม',
    prevMonth: 'เดือนก่อนหน้า',
    nextMonth: 'เดือนถัดไป',

    // Booking email notifications (subject/body generated in the actor's active language)
    emailActionCreated: 'ยืนยันการจองห้องประชุม',
    emailActionCancelled: 'ยกเลิกการจองห้องประชุม',
    emailActionUpdated: 'อัปเดตข้อมูลการจองห้องประชุม',
    emailLabelRoom: 'ห้องประชุม',
    emailLabelTopic: 'หัวข้อการประชุม',
    emailLabelBooker: 'ผู้ทำรายการ',
    emailLabelDept: 'แผนก',
    emailLabelDateTime: 'วันเวลา',
    emailFooterAutoSent: 'อีเมลฉบับนี้ส่งจากระบบจองห้องประชุม Villa Carte Group อัตโนมัติ (สำเนาถึงผู้ดูแลระบบ {adminEmail})',
    emailInvitePrefix: 'คำเชิญเข้าร่วมประชุม',
    emailInviteHeading: '📩 ท่านได้รับคำเชิญเข้าร่วมประชุม',
    emailInviteIntro: 'คุณ {name} ({email}) ได้เชิญท่านเข้าร่วมการประชุม:',
    emailInviteLabelLocation: 'สถานที่',
    emailInviteFooterSynced: 'ระบบได้ส่งคำเชิญและปฏิทินลงนัดใน Google Calendar ของท่านเรียบร้อยแล้ว',

    // Google Calendar event text (built outside React, via the plain `translations` object)
    calendarHeader: 'ระบบจองห้องประชุม Villa Carte Group',
    calendarHeaderUpdated: 'ระบบจองห้องประชุม Villa Carte Group (อัปเดตแล้ว)',
    calendarSummaryPrefix: 'จองห้องประชุม',
    calendarLabelAttendees: 'จำนวนผู้เข้าร่วม',
    calendarLabelNotes: 'หมายเหตุ',
    calendarLabelGuestEmails: 'อีเมลผู้เข้าร่วม',
    connectedGoogle: 'เชื่อมต่อกับ Google Workspace แล้ว',
    emailNotifications: 'การแจ้งเตือนอีเมล',
    adminActive: 'สิทธิ์ ADMIN',
    bookRoomBtn: '+ จองห้องประชุม',
    bookShort: 'จองห้อง',
    accountSettings: 'ตั้งค่าบัญชี Google',
    logoutBtn: 'ออกจากระบบ',
    // Sidebar
    brandSubtitle: 'ระบบจองห้องประชุม HQ',
    monthlySchedule: 'ตารางจองประจำเดือน',
    floorOverview: 'ผังห้องประชุม ชั้น 1 & 2',
    myReservations: 'การจองของฉัน',
    adminReports: 'รายงานและระบบผู้ดูแล',

    // Auth gate
    authGateDesc: 'ระบบจองห้องประชุม Villa Carte Group สงวนสิทธิ์เฉพาะพนักงานที่เข้าสู่ระบบด้วยอีเมลองค์กรเท่านั้น',
    authGateFooter: 'หากพบปัญหาการเข้าสู่ระบบ กรุณาติดต่อฝ่าย IT',

    // FloorPlan / Dashboard
    realtimeStatus: 'สถานะห้องประชุมเรียลไทม์',
    floorPlanTitle: 'ผังห้องประชุม อาคารสำนักงานใหญ่ (Villa Carte Group)',
    floorPlanDesc: 'อาคารมี 2 ชั้น รวม 5 ห้องประชุม พร้อมวิดีโอพรีวิวโครงการ Layan Verde',
    vacantNow: 'ห้องว่างขณะนี้',
    occupiedNow: 'ไม่ว่างกำลังใช้',
    totalRoomsCount: 'รวมทั้งหมด',
    pauseVideo: 'หยุดชั่วคราว',
    playVideo: 'เล่นวิดีโอ',
    unmute: 'เปิดเสียง',
    mute: 'ปิดเสียง',
    toggleBgVideo: 'สลับวิดีโอพื้นหลัง',
    turnOffVideo: 'ปิดวิดีโอ',
    turnOnVideo: 'เปิดวิดีโอ',
    floor1Label: 'ชั้น 1 (Floor 1)',
    floor2Label: 'ชั้น 2 (Floor 2)',
    bookThisRoom: 'จองห้องนี้',
    details: 'รายละเอียด',
    capacity: 'ความจุ',
    people: 'คน',
    floorSelectorLabel: 'ตัวเลือกแสดงชั้นห้องประชุม',
    showAllFloorsBtn: 'แสดงทุกชั้น (5 ห้อง)',
    floor1FilterBtn: 'ชั้น 1 (3 ห้อง)',
    floor2FilterBtn: 'ชั้น 2 (2 ห้อง)',
    floor1SectionDesc: 'ห้องประชุมใหญ่ ห้องประชุมเล็ก และห้องติดห้องเด็ก',
    floor2SectionDesc: '2 ห้องประชุมคณะกรรมการบริหาร & ห้องสร้างสรรค์ไอเดีย',
    floorBadge: 'ชั้น {floor}',
    statusOccupiedBadge: 'ไม่ว่าง (Occupied)',
    statusVacantBadge: 'ว่าง (Vacant)',
    maxCapacityLabel: 'ความจุสูงสุด {count} คน',
    occupiedNowLabel: 'กำลังใช้ห้องประชุมอยู่',
    untilLabel: 'ถึง {time}',
    bookedByLabel: 'ผู้จอง: {name}',
    upcomingTodayLabel: 'การจองถัดไปวันนี้',
    byLabel: 'โดย {name}',
    availableAllDayLabel: 'ห้องประชุมพร้อมใช้งานตลอดวันนี้',
    bookNowBadge: 'จองได้ทันที',
    viewScheduleBtn: 'ดูผังจอง',
    statusInUse: 'ไม่ว่าง',
    statusVacantShort: 'ว่าง',

    // BookingModal
    bookTitle: 'จองห้องประชุม',
    editTitle: 'แก้ไขการจองห้องประชุม',
    selectRoom: 'เลือกห้องประชุม',
    meetingTitle: 'หัวข้อการประชุม / เรื่องที่ประชุม',
    meetingTitlePlaceholder: 'เช่น สรุปผลยอดขายประจำเดือน, วางแผนการตลาด Q3',
    meetingDate: 'วันที่ประชุม',
    startTime: 'เวลาเริ่มต้น',
    endTime: 'เวลาสิ้นสุด',
    attendeesCount: 'จำนวนผู้เข้าร่วม (คน)',
    departmentTeam: 'แผนก / ทีม',
    cancel: 'ยกเลิก',
    confirmBooking: 'ยืนยันการจอง',
    saveChanges: 'บันทึกการแก้ไข',
    syncGoogleCal: 'ซิงค์กับ Google Calendar (ส่งคำเชิญลงนัดใน Google Calendar และอีเมล)',
    policyTitle: 'นโยบายจองห้องประชุม Villa Carte Group:',
    policyEmailNotice: 'ระบบจะส่งอีเมลแจ้งเตือนยืนยันไปยังผู้จองและผู้ดูแลระบบทันที',
    policyFloor1AdminOnly: 'ห้องประชุมชั้น 1 ทั้งหมดจองได้เฉพาะแอดมินเท่านั้น กรุณาติดต่อแอดมินหากต้องการใช้ห้องชั้น 1',
    validationErrorTitle: 'ไม่สามารถดำเนินการได้:',
    meetingTitleRequired: 'กรุณาระบุหัวข้อการประชุม',
    validationGeneric: 'ข้อมูลการจองไม่ถูกต้อง',
    validationEndBeforeStart: 'เวลาสิ้นสุดการประชุมต้องอยู่หลังเวลาเริ่มต้น (ระบบยังไม่รองรับการจองข้ามคืน)',
    validationAttendeesInvalid: 'จำนวนผู้เข้าร่วมต้องมากกว่า 0 คน',
    validationPastStart: 'ไม่สามารถจองเวลาที่ผ่านมาแล้วได้ กรุณาเลือกเวลาที่ยังไม่ถึง',
    validationFloor1AdminOnly: '{roomName} จองได้เฉพาะแอดมินเท่านั้น กรุณาติดต่อแอดมินเพื่อจองห้องนี้',
    validationCapacityExceeded: 'จำนวนผู้เข้าร่วมเกินความจุห้อง {roomName} (สูงสุด {capacity} คน)',
    validationOverlap: 'ช่วงเวลานี้มีการจองห้อง {roomName} แล้วโดย "{userName}" ({title} : {start} - {end})',
    durationLabel: 'ระยะเวลา: {hours} ชม.',
    bookerName: 'ผู้จอง',
    adminModeLabel: 'Admin Mode',
    descriptionPlaceholder: 'รายละเอียดเพิ่มเติม...',

    // GuestInviteSelector
    inviteGuestsLabel: 'เชิญผู้เข้าร่วมประชุมเพิ่มเติม / Google Email',
    invitedCount: 'เชิญแล้ว',
    searchGuestPlaceholder: 'ค้นหาชื่อ, แผนก หรือพิมพ์อีเมล (เช่น somchai, IT, guest@gmail.com)...',
    addEmailBtn: '+ เพิ่มอีเมล',
    invalidEmailError: 'รูปแบบอีเมลไม่ถูกต้อง',
    cannotInviteSelfError: 'ไม่สามารถเชิญตัวเองได้',
    emailAlreadyAddedError: 'เพิ่มอีเมลนี้ไว้แล้ว',
    invitedListTitle: 'รายชื่อผู้ที่ได้รับคำเชิญ',
    removeGuestTitle: 'ลบออกจากคำเชิญ',

    // MyBookings
    myBookingsTitle: 'รายการจองห้องประชุมของฉัน',
    account: 'ล็อกอินบัญชี',
    policyNote: 'นโยบายสิทธิ์: ผู้ใช้สามารถยกเลิกและแก้ไขได้เฉพาะการจองของตนเองเท่านั้น',
    upcomingTab: 'รายการที่จะเกิดขึ้น',
    pastTab: 'ประวัติการจองที่ผ่านมา',
    cancelledTab: 'รายการที่ยกเลิกแล้ว',
    edit: 'แก้ไข',
    cancelBooking: 'ยกเลิกการจอง',
    noBookingsFound: 'ไม่พบรายการจองห้องประชุมในหมวดนี้',
    startBookingHint: 'เริ่มต้นจองห้องประชุมได้จากปุ่ม "+ จองห้องประชุม" ด้านบน',
    confirmCancelTitle: 'ยืนยันการยกเลิกการจอง?',
    cancelNotice: 'ระบบจะทำการอัปเดตและแจ้งเตือนผ่านอีเมล',
    confirmCancelBtn: 'ใช่, ยกเลิกการจอง',
    confirmedStatus: 'ยืนยันแล้ว',
    cancelledStatus: 'ยกเลิกแล้ว',
    syncedGoogleCal: 'ซิงค์ Google Calendar แล้ว',
    invitedGuestsLabel: 'ผู้เข้าร่วมเพิ่มเติม',
    dateLabel: 'วันที่',
    timeLabel: 'เวลา',
    bookedByPrefix: 'จองโดย {name}',

    // MonthlySchedule
    monthlyTitle: 'ตารางการจองประจำเดือน',
    monthlyDesc: 'ดูภาพรวมการใช้งานห้องประชุมรายวันและรายเดือน',
    allRooms: 'ทุกห้องประชุม',
    monthView: 'มุมมองเดือน',
    weekView: 'มุมมองสัปดาห์',
    filterLabel: 'กรอง:',
    quickBookTooltip: 'คลิกจองในวันนี้',
    quickBookBtn: '+ จอง',
    noBookingsToday: 'ไม่มีการจอง',
    dayTimelineTitle: 'ผังเวลาประจำวัน ({date})',
    floorCapacityBadge: 'ชั้น {floor} ({capacity} คน)',
    dayBookRoomBtn: '+ จองห้องนี้',
    noBookingsTodayAvailable: 'ไม่มีการจองในวันนี้ — พร้อมใช้งาน',

    // AdminDashboard
    adminDashboardTitle: 'แดชบอร์ดผู้ดูแลระบบ (Admin Dashboard)',
    totalBookingsStat: 'การจองสะสมทั้งหมด',
    totalHoursStat: 'รวมชั่วโมงใช้งานจริง',
    roomColumn: 'ห้องประชุม',
    dateColumn: 'วันที่/เวลา',
    statusColumn: 'สถานะ',
    actionColumn: 'การจัดการ',
    exportExcel: 'Export Excel',
    exportPdf: 'Export PDF',
    adminBackOfficeBadge: 'Admin Back-Office',
    adminFullPrivilegesDesc: 'สิทธิ์ผู้ดูแลระบบเต็มรูปแบบ: ดู แก้ไข ลบการจอง วิเคราะห์สถิติรายเดือน และส่งออกรายงาน',
    confirmedCountLabel: '{count} รายการ',
    cancellationRateWithCount: 'อัตราการยกเลิก ({count} ครั้ง)',
    hoursPerRoomChartTitle: 'สรุปจำนวนชั่วโมงการใช้งานแยกตามห้องประชุม',
    hoursSeriesName: 'ชั่วโมงการใช้งาน',
    deptUsageChartTitle: 'สัดส่วนการจองใช้งานแยกตามแผนก/ฝ่าย',
    masterLogsTitle: 'รายการประวัติการจองทั้งหมด (Master Booking Logs)',
    masterLogsDesc: 'สามารถค้นหา กรองข้อมูล แก้ไข หรือลบรายการของผู้ใช้ได้ทุกกรณี',
    searchPlaceholderAdmin: 'ค้นหาตามหัวข้อประชุม, ชื่อผู้จอง, อีเมล, แผนก...',
    allRoomsFilterOption: 'กรองตามห้องประชุม (ทั้งหมด)',
    allStatusFilterOption: 'สถานะทั้งหมด',
    confirmedFilterOption: 'อนุมัติแล้ว (Confirmed)',
    cancelledFilterOption: 'ยกเลิกแล้ว (Cancelled)',
    floorShort: 'ชั้น {floor}',
    statusConfirmedPill: 'ยืนยันแล้ว',
    statusCancelledPill: 'ยกเลิกแล้ว',
    editActionTitle: 'แก้ไขรายการนี้ (Admin)',
    deleteActionTitle: 'ลบรายการนี้เป็นการถาวร (Admin)',
    noResultsFound: 'ไม่พบรายการจองที่ตรงกับเงื่อนไขการค้นหา',
    deleteConfirmTitle: 'ยืนยันลบการจองเป็นการถาวร?',
    deleteConfirmDesc: 'คุณกำลังจะลบการจอง "{title}" ของผู้ใช้ {name}',
    deleteConfirmNotice: 'การลบด้วยสิทธิ์ Admin จะลบข้อมูลออกจากฐานข้อมูลทันที และระบบจะส่งอีเมลแจ้งเตือนการยกเลิก/ลบไปยังผู้ใช้',
    deleteConfirmBtn: 'ลบข้อมูลทันที',
    hoursUnit: 'ชม.',
    itemsUnit: 'รายการ',

    // GoogleAuthModal
    ssoTitle: 'เข้าสู่ระบบด้วย Google Account',
    ssoDesc: 'เชื่อมต่อบัญชี Google ของคุณเพื่อซิงค์กิจกรรมลง Google Calendar และส่งคำเชิญทางอีเมลโดยอัตโนมัติ',
    ssoReconnectTitle: 'เชื่อมต่อ Google Calendar อีกครั้ง',
    ssoReconnectDesc: 'การเชื่อมต่อ Google Calendar ของคุณหมดอายุแล้ว กรุณากดปุ่มด้านล่างเพื่อเชื่อมต่อใหม่ (ไม่ต้องเลือกแผนกซ้ำ)',
    ssoConnectedTitle: 'Google Calendar',
    ssoConnectedDesc: 'บัญชี Google ของคุณเชื่อมต่อกับระบบอยู่แล้ว',
    loginGoogleBtn: 'เข้าสู่ระบบด้วย Google',
    reconnectGoogleBtn: 'เชื่อมต่อ Google Calendar อีกครั้ง',
    googleCalendarConnectedStatus: 'เชื่อมต่อ Google Calendar อยู่',
    googleCalendarConnectedDetail: 'การจองของคุณจะถูกซิงค์เข้า Google Calendar โดยอัตโนมัติ ไม่ต้องเข้าสู่ระบบซ้ำ',
    connectingLabel: 'กำลังเชื่อมต่อ...',
    departmentLabel: 'แผนก / ฝ่าย',
    errorGoogleGeneric: 'ไม่สามารถเข้าสู่ระบบด้วย Google ได้: {msg}',
    ssoFooterAuth: 'ระบบยืนยันตัวตนและฐานข้อมูล PocketBase (Self-hosted)',
    adminEmailLabel: 'Admin',

    // EmailDrawer
    emailDrawerSubtitle: 'การแจ้งเตือนอัตโนมัติสำหรับการจองห้องประชุม',
    noEmails: 'ไม่มีรายการแจ้งเตือนอีเมลในขณะนี้',
    noEmailsDesc: 'เมื่อคุณทำการจองหรือยกเลิกการจอง อีเมลแจ้งเตือนจะปรากฏที่นี่',
    markAllRead: 'อ่านแล้วทั้งหมด',
    toLabel: 'ถึง',
    fromSystemLabel: 'ผู้ส่ง: Villa Carte Group Notification System',
    clearBtn: 'ล้างข้อความ',
    adminCopyNotice: 'สำเนาอีเมลจะถูกจัดส่งไปยังผู้ดูแลระบบ {email}',

    // App-level toasts & misc
    bookingCreateFailedToast: 'ไม่สามารถบันทึกการจองได้ กรุณาลองใหม่อีกครั้ง',
    bookingRaceConditionToast: 'มีคนจองห้องนี้ในเวลาเดียวกันไปก่อนหน้าคุณเพียงเสี้ยววินาที กรุณาเลือกเวลาหรือห้องอื่น',
    bookingCreatedToast: 'ลงทะเบียนจอง "{title}" ในระบบสำเร็จ!',
    bookingCreatedGCalToast: 'ลงทะเบียนจองและซิงค์ Google Calendar สำเร็จ!',
    bookingUpdatedToast: 'อัปเดตข้อมูลการจองเรียบร้อยแล้ว',
    bookingCancelledToast: 'ยกเลิกการจอง "{title}" ในระบบแล้ว',
    bookingDeletedToast: 'ลบข้อมูลการจองออกจากระบบแล้ว',
    notificationsMarkedReadToast: 'ทำเครื่องหมายว่าอ่านแล้วทั้งหมด',
    notificationsClearedToast: 'ล้างกล่องข้อความแจ้งเตือนแล้ว',
    notificationsActionFailedToast: 'ดำเนินการกับข้อความแจ้งเตือนบางรายการไม่สำเร็จ กรุณาลองใหม่อีกครั้ง',
    emailNotificationFailedToast: 'ไม่สามารถส่งอีเมลแจ้งเตือนได้ กรุณาลองใหม่อีกครั้ง',
    signedInAsToast: 'ลงชื่อเข้าใช้ในนาม "{name}" ({email})',
    sessionExpiredToast: 'เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่อีกครั้ง',
    googleAuthNotice: 'กรุณาเข้าสู่ระบบด้วย Google (ปุ่มมุมขวาบน) เพื่อให้ระบบส่งคำเชิญลง Google Calendar และแจ้งเตือนอีเมลจริงไปยังผู้เข้าร่วม',
    googleCalendarSyncExpiredToast: 'การเชื่อมต่อ Google Calendar หมดอายุ กรุณาเชื่อมต่อใหม่อีกครั้งเพื่อให้ลงนัดในปฏิทินได้ (การจองของคุณบันทึกสำเร็จแล้ว)',
    googleCalendarSyncFailedToast: 'ไม่สามารถลงนัดใน Google Calendar ได้ (การจองของคุณบันทึกสำเร็จแล้ว)',
    googleCalendarDisconnectedWarning: 'การเชื่อมต่อ Google Calendar ยังไม่ได้เชื่อมต่อหรือหมดอายุ — การจองนี้จะบันทึกได้ปกติ แต่จะไม่ถูกส่งเข้า Google Calendar จนกว่าจะเชื่อมต่อใหม่',
    viewDetailTitle: 'รายละเอียดการจองห้องประชุม',
    viewDetailIdLabel: 'ID',
    roomLabel: 'ห้องประชุม',
    dateTimeLabel: 'วันที่ & เวลา',
    additionalGuestsLabel: 'ผู้เข้าร่วมเพิ่มเติม (Google Emails)',
    syncedToGCalLabel: 'ซิงค์ลง Google Calendar แล้ว',
    openInGCalLabel: 'เปิดใน Google Calendar ↗',
    closeBtn: 'ปิดหน้าต่าง',
    legendStandard: 'Standard: การจองของผู้ใช้ทั่วไป',
    legendAdmin: 'Admin: การจองสิทธิ์ผู้ดูแลระบบ',
    legendVacant: 'Vacant: ห้องว่างพร้อมให้จอง',
    footerSummary: 'แสดงสรุปข้อมูลประจำเดือนของ Villa Carte Group Workspace',
    mobileNavSchedule: 'ตาราง',
    mobileNavRooms: 'ภาพรวม',
    mobileNavMyBookings: 'การจองของฉัน',
    mobileNavHelpdesk: 'แจ้งปัญหา',
    mobileNavAdmin: 'แอดมิน',

    // IT Helpdesk
    helpdeskNav: 'แจ้งปัญหา IT',
    helpdeskTitle: 'IT Helpdesk',
    helpdeskSubtitle: 'แจ้งปัญหา/ขออุปกรณ์จากฝ่าย IT และติดตามสถานะ',
    newTicketBtn: '+ แจ้งปัญหาใหม่',
    ticketStatusOpen: 'รอดำเนินการ',
    ticketStatusInProgress: 'กำลังดำเนินการ',
    ticketStatusResolved: 'แก้ไขแล้ว',
    ticketStatusClosed: 'ปิดงาน',
    ticketCategoryHardware: 'ฮาร์ดแวร์',
    ticketCategorySoftware: 'ซอฟต์แวร์',
    ticketCategoryNetwork: 'เครือข่าย',
    ticketCategoryAccount: 'บัญชีผู้ใช้',
    ticketCategoryOther: 'อื่นๆ',
    ticketPriorityLow: 'ต่ำ',
    ticketPriorityMedium: 'ปานกลาง',
    ticketPriorityHigh: 'สูง',
    ticketPriorityUrgent: 'ด่วนมาก',
    noTicketsFound: 'ไม่มีรายการในหมวดนี้',
    ticketRequestedBy: 'แจ้งโดย',
    ticketResolutionNotesLabel: 'บันทึกการแก้ไข',
    ticketResolvedByLabel: 'แก้ไขโดย',
    ticketResolutionNotesPlaceholder: 'บันทึกวิธีแก้ไข (จะส่งอีเมลแจ้งผู้แจ้งเมื่อกดแก้ไขแล้ว)',
    ticketAssignToMeBtn: 'รับงานนี้',
    ticketMarkResolvedBtn: 'แก้ไขแล้ว',
    ticketMarkClosedBtn: 'ปิดงาน',
    ticketReopenBtn: 'เปิดใหม่อีกครั้ง',
    newTicketModalTitle: 'แจ้งปัญหาใหม่',
    ticketTitleLabel: 'หัวข้อ',
    ticketTitlePlaceholder: 'เช่น คอมพิวเตอร์เปิดไม่ติด',
    ticketDescriptionLabel: 'รายละเอียด',
    ticketDescriptionPlaceholder: 'อธิบายปัญหาที่พบโดยละเอียด',
    ticketCategoryLabel: 'ประเภท',
    ticketPriorityLabel: 'ความเร่งด่วน',
    submitTicketBtn: 'ส่งเรื่องแจ้งปัญหา',
    ticketTitleRequired: 'กรุณากรอกหัวข้อและรายละเอียด',
    ticketCreatedToast: 'ส่งเรื่องแจ้งปัญหาเรียบร้อยแล้ว',
    ticketUpdatedToast: 'อัปเดตสถานะเรียบร้อย',
    ticketErrorToast: 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง',
  },
  en: {
    // Header
    consoleTitle: 'Meeting Room Booking',
    subtitle: 'Villa Carte Group HQ • Floor 1 & 2',
    bookingModalSubtitle: 'HQ Workspace Console • Villa Carte Group',
    ssoSubtitle: 'Villa Carte Group Single Sign-On',
    prevMonth: 'Previous month',
    nextMonth: 'Next month',

    // Booking email notifications (subject/body generated in the actor's active language)
    emailActionCreated: 'Meeting Room Booking Confirmed',
    emailActionCancelled: 'Meeting Room Booking Cancelled',
    emailActionUpdated: 'Meeting Room Booking Updated',
    emailLabelRoom: 'Room',
    emailLabelTopic: 'Meeting Topic',
    emailLabelBooker: 'Booked By',
    emailLabelDept: 'Department',
    emailLabelDateTime: 'Date & Time',
    emailFooterAutoSent: 'This email was sent automatically by the Villa Carte Group meeting room booking system (cc: admin {adminEmail})',
    emailInvitePrefix: 'Meeting Invite',
    emailInviteHeading: "📩 You've been invited to a meeting",
    emailInviteIntro: '{name} ({email}) has invited you to a meeting:',
    emailInviteLabelLocation: 'Location',
    emailInviteFooterSynced: 'This invite has been added to your Google Calendar.',

    // Google Calendar event text (built outside React, via the plain `translations` object)
    calendarHeader: 'Villa Carte Group Meeting Room Booking',
    calendarHeaderUpdated: 'Villa Carte Group Meeting Room Booking (Updated)',
    calendarSummaryPrefix: 'Room Booking',
    calendarLabelAttendees: 'Attendees',
    calendarLabelNotes: 'Notes',
    calendarLabelGuestEmails: 'Guest Emails',
    connectedGoogle: 'Connected to Google Workspace',
    emailNotifications: 'Email Notifications',
    adminActive: 'ADMIN',
    bookRoomBtn: '+ Book a Room',
    bookShort: 'Book',
    accountSettings: 'Google Account Settings',
    logoutBtn: 'Log Out',
    // Sidebar
    brandSubtitle: 'HQ Room Booking System',
    monthlySchedule: 'Monthly Schedule',
    floorOverview: 'Floor 1 & 2 Overview',
    myReservations: 'My Bookings',
    adminReports: 'Reports & Administration',

    // Auth gate
    authGateDesc: 'The Villa Carte Group meeting room booking system is restricted to employees signed in with their company email.',
    authGateFooter: 'Having trouble signing in? Contact the IT department.',

    // FloorPlan / Dashboard
    realtimeStatus: 'Real-Time Room Status',
    floorPlanTitle: 'Meeting Room Floor Plan (Villa Carte Group HQ)',
    floorPlanDesc: 'A 2-floor building with 5 meeting rooms, featuring a Layan Verde project preview video',
    vacantNow: 'Vacant Now',
    occupiedNow: 'Occupied Now',
    totalRoomsCount: 'Total Rooms',
    pauseVideo: 'Pause',
    playVideo: 'Play',
    unmute: 'Unmute',
    mute: 'Mute',
    toggleBgVideo: 'Toggle Background Video',
    turnOffVideo: 'Turn Off Video',
    turnOnVideo: 'Turn On Video',
    floor1Label: 'Floor 1',
    floor2Label: 'Floor 2',
    bookThisRoom: 'Book This Room',
    details: 'Details',
    capacity: 'Capacity',
    people: 'people',
    floorSelectorLabel: 'Filter by Floor',
    showAllFloorsBtn: 'All Floors (5 rooms)',
    floor1FilterBtn: 'Floor 1 (3 rooms)',
    floor2FilterBtn: 'Floor 2 (2 rooms)',
    floor1SectionDesc: 'A big meeting room, a small meeting room & a kids-room-adjacent room',
    floor2SectionDesc: '2 executive/board rooms & a creative hub',
    floorBadge: 'Floor {floor}',
    statusOccupiedBadge: 'Occupied',
    statusVacantBadge: 'Vacant',
    maxCapacityLabel: 'Max capacity {count} people',
    occupiedNowLabel: 'Currently in use',
    untilLabel: 'Until {time}',
    bookedByLabel: 'Booked by: {name}',
    upcomingTodayLabel: 'Upcoming today',
    byLabel: 'By {name}',
    availableAllDayLabel: 'Available all day today',
    bookNowBadge: 'Book instantly',
    viewScheduleBtn: 'View Schedule',
    statusInUse: 'In Use',
    statusVacantShort: 'Vacant',

    // BookingModal
    bookTitle: 'Book a Meeting Room',
    editTitle: 'Edit Booking',
    selectRoom: 'Select a Room',
    meetingTitle: 'Meeting Title / Topic',
    meetingTitlePlaceholder: 'e.g. Monthly Sales Review, Q3 Marketing Plan',
    meetingDate: 'Meeting Date',
    startTime: 'Start Time',
    endTime: 'End Time',
    attendeesCount: 'Number of Attendees',
    departmentTeam: 'Department / Team',
    cancel: 'Cancel',
    confirmBooking: 'Confirm Booking',
    saveChanges: 'Save Changes',
    syncGoogleCal: 'Sync with Google Calendar (send invites to attendees)',
    policyTitle: 'Villa Carte Group booking policy:',
    policyEmailNotice: 'A confirmation email will be sent to the booker and the administrator immediately',
    policyFloor1AdminOnly: 'All Floor 1 rooms can only be booked by an admin. Please contact the admin if you need a Floor 1 room.',
    validationErrorTitle: 'Unable to proceed:',
    meetingTitleRequired: 'Please enter a meeting title',
    validationGeneric: 'Invalid booking details',
    validationEndBeforeStart: 'The end time must be after the start time (overnight bookings aren\'t supported yet)',
    validationAttendeesInvalid: 'The number of attendees must be greater than 0',
    validationPastStart: 'You cannot book a time slot that has already passed — please choose a future time.',
    validationFloor1AdminOnly: '{roomName} can only be booked by an admin. Please contact the admin to book this room.',
    validationCapacityExceeded: 'Attendee count exceeds the capacity of {roomName} (max {capacity} people)',
    validationOverlap: 'This time slot in {roomName} is already booked by "{userName}" ({title}: {start} - {end})',
    durationLabel: 'Duration: {hours} hrs',
    bookerName: 'Booked by',
    adminModeLabel: 'Admin Mode',
    descriptionPlaceholder: 'Additional details...',

    // GuestInviteSelector
    inviteGuestsLabel: 'Invite Additional Attendees / Google Email',
    invitedCount: 'Invited',
    searchGuestPlaceholder: 'Search name, department, or type an email (e.g. somchai, IT, guest@gmail.com)...',
    addEmailBtn: '+ Add Email',
    invalidEmailError: 'Invalid email format',
    cannotInviteSelfError: 'You cannot invite yourself',
    emailAlreadyAddedError: 'This email has already been added',
    invitedListTitle: 'Invited Attendees',
    removeGuestTitle: 'Remove from invite',

    // MyBookings
    myBookingsTitle: 'My Meeting Room Bookings',
    account: 'Signed in as',
    policyNote: 'Policy: users may only edit or cancel their own bookings',
    upcomingTab: 'Upcoming',
    pastTab: 'Past Bookings',
    cancelledTab: 'Cancelled',
    edit: 'Edit',
    cancelBooking: 'Cancel Booking',
    noBookingsFound: 'No bookings found in this category',
    startBookingHint: 'Start by clicking "+ Book a Room" above',
    confirmCancelTitle: 'Cancel this booking?',
    cancelNotice: 'This will update the booking and notify attendees by email.',
    confirmCancelBtn: 'Yes, cancel booking',
    confirmedStatus: 'Confirmed',
    cancelledStatus: 'Cancelled',
    syncedGoogleCal: 'Synced to Google Calendar',
    invitedGuestsLabel: 'Additional Attendees',
    dateLabel: 'Date',
    timeLabel: 'Time',
    bookedByPrefix: 'Booked by {name}',

    // MonthlySchedule
    monthlyTitle: 'Monthly Room Schedule',
    monthlyDesc: 'View daily and monthly meeting room usage at a glance',
    allRooms: 'All Rooms',
    monthView: 'Month View',
    weekView: 'Day View',
    filterLabel: 'Filter:',
    quickBookTooltip: 'Click to book on this day',
    quickBookBtn: '+ Book',
    noBookingsToday: 'No bookings',
    dayTimelineTitle: 'Daily Timeline ({date})',
    floorCapacityBadge: 'Floor {floor} ({capacity} people)',
    dayBookRoomBtn: '+ Book This Room',
    noBookingsTodayAvailable: 'No bookings today — available',

    // AdminDashboard
    adminDashboardTitle: 'Admin Dashboard',
    totalBookingsStat: 'Total Bookings',
    totalHoursStat: 'Total Hours Used',
    roomColumn: 'Room',
    dateColumn: 'Date/Time',
    statusColumn: 'Status',
    actionColumn: 'Actions',
    exportExcel: 'Export Excel',
    exportPdf: 'Export PDF',
    adminBackOfficeBadge: 'Admin Back-Office',
    adminFullPrivilegesDesc: 'Full administrative privileges to view, edit, delete bookings, analyze monthly stats, and export reports.',
    confirmedCountLabel: '{count} bookings',
    cancellationRateWithCount: 'Cancellation rate ({count} bookings)',
    hoursPerRoomChartTitle: 'Hours Used per Room',
    hoursSeriesName: 'Hours Used',
    deptUsageChartTitle: 'Bookings by Department',
    masterLogsTitle: 'Master Booking Logs',
    masterLogsDesc: 'Search, filter, edit, or delete any booking in the system',
    searchPlaceholderAdmin: 'Search by title, booker name, email, department...',
    allRoomsFilterOption: 'All Rooms',
    allStatusFilterOption: 'All Statuses',
    confirmedFilterOption: 'Confirmed',
    cancelledFilterOption: 'Cancelled',
    floorShort: 'Floor {floor}',
    statusConfirmedPill: 'Confirmed',
    statusCancelledPill: 'Cancelled',
    editActionTitle: 'Edit this booking (Admin)',
    deleteActionTitle: 'Permanently delete this booking (Admin)',
    noResultsFound: 'No bookings match your search criteria',
    deleteConfirmTitle: 'Permanently delete this booking?',
    deleteConfirmDesc: 'You are about to delete "{title}" booked by {name}',
    deleteConfirmNotice: 'Deleting as Admin removes this record immediately and notifies the user by email.',
    deleteConfirmBtn: 'Delete Now',
    hoursUnit: 'hrs',
    itemsUnit: 'bookings',

    // GoogleAuthModal
    ssoTitle: 'Sign in with your Google Account',
    ssoDesc: 'Connect your Google account to automatically sync events to Google Calendar and send email invites.',
    ssoReconnectTitle: 'Reconnect Google Calendar',
    ssoReconnectDesc: 'Your Google Calendar connection has expired. Click below to reconnect (no need to pick your department again).',
    ssoConnectedTitle: 'Google Calendar',
    ssoConnectedDesc: 'Your Google account is already connected.',
    loginGoogleBtn: 'Sign in with Google',
    reconnectGoogleBtn: 'Reconnect Google Calendar',
    googleCalendarConnectedStatus: 'Google Calendar is connected',
    googleCalendarConnectedDetail: 'Your bookings sync to Google Calendar automatically — no need to sign in again.',
    connectingLabel: 'Connecting...',
    departmentLabel: 'Department',
    errorGoogleGeneric: 'Could not sign in with Google: {msg}',
    ssoFooterAuth: 'Self-hosted PocketBase (Auth & Database)',
    adminEmailLabel: 'Admin',

    // EmailDrawer
    emailDrawerSubtitle: 'Automatic notifications for room bookings',
    noEmails: 'No email notifications yet',
    noEmailsDesc: 'When you book or cancel a room, notifications will appear here',
    markAllRead: 'Mark all read',
    toLabel: 'To',
    fromSystemLabel: 'From: Villa Carte Group Notification System',
    clearBtn: 'Clear',
    adminCopyNotice: 'A copy of this email is sent to the administrator {email}',

    // App-level toasts & misc
    bookingCreateFailedToast: 'Could not save the booking. Please try again.',
    bookingRaceConditionToast: 'Someone else booked this room for the same time just before you. Please choose a different time or room.',
    bookingCreatedToast: 'Booking "{title}" was created successfully!',
    bookingCreatedGCalToast: 'Booking created and synced to Google Calendar!',
    bookingUpdatedToast: 'Booking updated successfully',
    bookingCancelledToast: 'Booking "{title}" has been cancelled',
    bookingDeletedToast: 'Booking deleted from the system',
    notificationsMarkedReadToast: 'All notifications marked as read',
    notificationsClearedToast: 'Notification inbox cleared',
    notificationsActionFailedToast: 'Could not update some notifications. Please try again.',
    emailNotificationFailedToast: 'Could not send the email notification. Please try again.',
    signedInAsToast: 'Signed in as "{name}" ({email})',
    sessionExpiredToast: 'Your session has expired. Please sign in again.',
    googleAuthNotice: 'Please sign in with Google (top-right button) so the system can send Google Calendar invites and real email notifications to attendees',
    googleCalendarSyncExpiredToast: 'Your Google Calendar connection has expired. Please reconnect to sync this booking to your calendar (your booking has already been saved).',
    googleCalendarSyncFailedToast: 'Could not sync this booking to Google Calendar (your booking has already been saved).',
    googleCalendarDisconnectedWarning: 'Google Calendar is not connected or your connection has expired — this booking will still be saved, but it won\'t be sent to Google Calendar until you reconnect.',
    viewDetailTitle: 'Booking Details',
    viewDetailIdLabel: 'ID',
    roomLabel: 'Room',
    dateTimeLabel: 'Date & Time',
    additionalGuestsLabel: 'Additional Attendees (Google Emails)',
    syncedToGCalLabel: 'Synced to Google Calendar',
    openInGCalLabel: 'Open in Google Calendar ↗',
    closeBtn: 'Close',
    legendStandard: 'Standard: regular user booking',
    legendAdmin: 'Admin: administrator booking',
    legendVacant: 'Vacant: available for booking',
    footerSummary: 'Showing current month summary for Villa Carte Group Workspace',
    mobileNavSchedule: 'Schedule',
    mobileNavRooms: 'Overview',
    mobileNavMyBookings: 'My Bookings',
    mobileNavHelpdesk: 'Helpdesk',
    mobileNavAdmin: 'Admin',

    // IT Helpdesk
    helpdeskNav: 'IT Helpdesk',
    helpdeskTitle: 'IT Helpdesk',
    helpdeskSubtitle: 'Report an issue or request help from IT and track its status',
    newTicketBtn: '+ New Ticket',
    ticketStatusOpen: 'Open',
    ticketStatusInProgress: 'In Progress',
    ticketStatusResolved: 'Resolved',
    ticketStatusClosed: 'Closed',
    ticketCategoryHardware: 'Hardware',
    ticketCategorySoftware: 'Software',
    ticketCategoryNetwork: 'Network',
    ticketCategoryAccount: 'Account',
    ticketCategoryOther: 'Other',
    ticketPriorityLow: 'Low',
    ticketPriorityMedium: 'Medium',
    ticketPriorityHigh: 'High',
    ticketPriorityUrgent: 'Urgent',
    noTicketsFound: 'No tickets in this category',
    ticketRequestedBy: 'Requested by',
    ticketResolutionNotesLabel: 'Resolution Notes',
    ticketResolvedByLabel: 'Resolved by',
    ticketResolutionNotesPlaceholder: 'Notes on how this was resolved (emailed to the requester once marked resolved)',
    ticketAssignToMeBtn: 'Assign to Me',
    ticketMarkResolvedBtn: 'Mark Resolved',
    ticketMarkClosedBtn: 'Close Ticket',
    ticketReopenBtn: 'Reopen',
    newTicketModalTitle: 'New Ticket',
    ticketTitleLabel: 'Title',
    ticketTitlePlaceholder: 'e.g. My computer won\'t turn on',
    ticketDescriptionLabel: 'Description',
    ticketDescriptionPlaceholder: 'Describe the issue in detail',
    ticketCategoryLabel: 'Category',
    ticketPriorityLabel: 'Priority',
    submitTicketBtn: 'Submit Ticket',
    ticketTitleRequired: 'Please fill in the title and description',
    ticketCreatedToast: 'Ticket submitted.',
    ticketUpdatedToast: 'Ticket updated',
    ticketErrorToast: 'Something went wrong. Please try again.',
  },
  ru: {
    // Header
    consoleTitle: 'Бронирование конференц-залов',
    subtitle: 'Штаб-квартира Villa Carte Group • 1 и 2 этажи',
    bookingModalSubtitle: 'Рабочая консоль HQ • Villa Carte Group',
    ssoSubtitle: 'Единый вход Villa Carte Group',
    prevMonth: 'Предыдущий месяц',
    nextMonth: 'Следующий месяц',

    // Booking email notifications (subject/body generated in the actor's active language)
    emailActionCreated: 'Подтверждение бронирования переговорной',
    emailActionCancelled: 'Отмена бронирования переговорной',
    emailActionUpdated: 'Изменение бронирования переговорной',
    emailLabelRoom: 'Переговорная',
    emailLabelTopic: 'Тема встречи',
    emailLabelBooker: 'Организатор',
    emailLabelDept: 'Отдел',
    emailLabelDateTime: 'Дата и время',
    emailFooterAutoSent: 'Это письмо отправлено автоматически системой бронирования переговорных Villa Carte Group (копия администратору {adminEmail})',
    emailInvitePrefix: 'Приглашение на встречу',
    emailInviteHeading: '📩 Вас пригласили на встречу',
    emailInviteIntro: '{name} ({email}) приглашает вас на встречу:',
    emailInviteLabelLocation: 'Место проведения',
    emailInviteFooterSynced: 'Приглашение уже добавлено в ваш Google Календарь.',

    // Google Calendar event text (built outside React, via the plain `translations` object)
    calendarHeader: 'Бронирование переговорной Villa Carte Group',
    calendarHeaderUpdated: 'Бронирование переговорной Villa Carte Group (обновлено)',
    calendarSummaryPrefix: 'Бронь переговорной',
    calendarLabelAttendees: 'Количество участников',
    calendarLabelNotes: 'Примечание',
    calendarLabelGuestEmails: 'Email участников',
    connectedGoogle: 'Подключено к Google Workspace',
    emailNotifications: 'Уведомления по Email',
    adminActive: 'Права ADMIN',
    bookRoomBtn: '+ Забронировать зал',
    bookShort: 'Забронировать',
    accountSettings: 'Настройки аккаунта Google',
    logoutBtn: 'Выйти',
    // Sidebar
    brandSubtitle: 'Система бронирования HQ',
    monthlySchedule: 'Месячный график',
    floorOverview: 'План залов 1 и 2 этажа',
    myReservations: 'Мои бронирования',
    adminReports: 'Отчеты и Администрирование',

    // Auth gate
    authGateDesc: 'Система бронирования конференц-залов Villa Carte Group доступна только сотрудникам, вошедшим через корпоративную почту.',
    authGateFooter: 'Проблемы со входом? Обратитесь в IT-отдел.',

    // FloorPlan / Dashboard
    realtimeStatus: 'Статус залов в реальном времени',
    floorPlanTitle: 'План конференц-залов Главного офиса (Villa Carte Group)',
    floorPlanDesc: '2 этажа, 5 переговорных. Видео-превью премиум-комплекса Layan Verde',
    vacantNow: 'Свободно сейчас',
    occupiedNow: 'Занято сейчас',
    totalRoomsCount: 'Всего залов',
    pauseVideo: 'Пауза',
    playVideo: 'Воспроизвести',
    unmute: 'Включить звук',
    mute: 'Выключить звук',
    toggleBgVideo: 'Фоновое видео',
    turnOffVideo: 'Выключить видео',
    turnOnVideo: 'Включить видео',
    floor1Label: '1 этаж',
    floor2Label: '2 этаж',
    bookThisRoom: 'Забронировать зал',
    details: 'Подробности',
    capacity: 'Вместимость',
    people: 'чел.',
    floorSelectorLabel: 'Фильтр по этажу',
    showAllFloorsBtn: 'Все этажи (5 залов)',
    floor1FilterBtn: '1 этаж (3 зала)',
    floor2FilterBtn: '2 этаж (2 зала)',
    floor1SectionDesc: 'Большой зал, малый зал и зал у детской комнаты',
    floor2SectionDesc: '2 зала для руководства и творческий хаб',
    floorBadge: '{floor} этаж',
    statusOccupiedBadge: 'Занято',
    statusVacantBadge: 'Свободно',
    maxCapacityLabel: 'Вместимость до {count} чел.',
    occupiedNowLabel: 'Сейчас идёт встреча',
    untilLabel: 'До {time}',
    bookedByLabel: 'Забронировал: {name}',
    upcomingTodayLabel: 'Ближайшая встреча сегодня',
    byLabel: 'От {name}',
    availableAllDayLabel: 'Свободен весь день сегодня',
    bookNowBadge: 'Забронировать сейчас',
    viewScheduleBtn: 'Расписание',
    statusInUse: 'Занято',
    statusVacantShort: 'Свободно',

    // BookingModal
    bookTitle: 'Бронирование конференц-зала',
    editTitle: 'Редактирование бронирования',
    selectRoom: 'Выберите конференц-зал',
    meetingTitle: 'Тема встречи / Повестка дня',
    meetingTitlePlaceholder: 'Например: Подведение итогов продаж, Маркетинг Q3',
    meetingDate: 'Дата встречи',
    startTime: 'Время начала',
    endTime: 'Время окончания',
    attendeesCount: 'Количество участников (чел.)',
    departmentTeam: 'Отдел / Команда',
    cancel: 'Отмена',
    confirmBooking: 'Подтвердить бронь',
    saveChanges: 'Сохранить изменения',
    syncGoogleCal: 'Синхронизировать с Google Calendar (отправить приглашения в календарь и по email)',
    policyTitle: 'Правила бронирования Villa Carte Group:',
    policyEmailNotice: 'Письмо с подтверждением сразу отправится заявителю и администратору',
    policyFloor1AdminOnly: 'Все переговорные на 1 этаже может забронировать только администратор. Обратитесь к администратору, если вам нужна комната на 1 этаже.',
    validationErrorTitle: 'Невозможно выполнить:',
    meetingTitleRequired: 'Пожалуйста, укажите тему встречи',
    validationGeneric: 'Некорректные данные бронирования',
    validationEndBeforeStart: 'Время окончания должно быть позже времени начала (ночные бронирования пока не поддерживаются)',
    validationAttendeesInvalid: 'Количество участников должно быть больше 0',
    validationPastStart: 'Нельзя забронировать время, которое уже прошло — выберите время в будущем.',
    validationFloor1AdminOnly: '{roomName} может забронировать только администратор. Обратитесь к администратору для бронирования этой комнаты.',
    validationCapacityExceeded: 'Количество участников превышает вместимость {roomName} (макс. {capacity} чел.)',
    validationOverlap: 'Это время в {roomName} уже занято "{userName}" ({title}: {start} - {end})',
    durationLabel: 'Продолжительность: {hours} ч.',
    bookerName: 'Заявитель',
    adminModeLabel: 'Режим администратора',
    descriptionPlaceholder: 'Дополнительные детали...',

    // GuestInviteSelector
    inviteGuestsLabel: 'Пригласить участников / Email',
    invitedCount: 'Приглашено',
    searchGuestPlaceholder: 'Поиск по имени, отделу или email (напр. somchai, IT, guest@gmail.com)...',
    addEmailBtn: '+ Добавить email',
    invalidEmailError: 'Неверный формат email',
    cannotInviteSelfError: 'Нельзя пригласить самого себя',
    emailAlreadyAddedError: 'Этот email уже добавлен',
    invitedListTitle: 'Список приглашенных участников',
    removeGuestTitle: 'Убрать из приглашённых',

    // MyBookings
    myBookingsTitle: 'Мои бронирования залов',
    account: 'Вы вошли как',
    policyNote: 'Правила доступа: пользователи могут отменять и редактировать только свои брони.',
    upcomingTab: 'Предстоящие',
    pastTab: 'Прошедшие',
    cancelledTab: 'Отменённые',
    edit: 'Изменить',
    cancelBooking: 'Отменить бронь',
    noBookingsFound: 'В этой категории бронирования не найдены',
    startBookingHint: 'Начните с кнопки "+ Забронировать зал" выше',
    confirmCancelTitle: 'Подтвердить отмену бронирования?',
    cancelNotice: 'Участники получат уведомление по email.',
    confirmCancelBtn: 'Да, отменить бронь',
    confirmedStatus: 'Подтверждено',
    cancelledStatus: 'Отменено',
    syncedGoogleCal: 'Синхронизировано с Google Calendar',
    invitedGuestsLabel: 'Дополнительные участники',
    dateLabel: 'Дата',
    timeLabel: 'Время',
    bookedByPrefix: 'Забронировал {name}',

    // MonthlySchedule
    monthlyTitle: 'Месячное расписание залов',
    monthlyDesc: 'Обзор загруженности конференц-залов по дням и месяцам',
    allRooms: 'Все конференц-залы',
    monthView: 'Месяц',
    weekView: 'День',
    filterLabel: 'Фильтр:',
    quickBookTooltip: 'Нажмите, чтобы забронировать этот день',
    quickBookBtn: '+ Забронировать',
    noBookingsToday: 'Нет броней',
    dayTimelineTitle: 'Расписание дня ({date})',
    floorCapacityBadge: '{floor} этаж ({capacity} чел.)',
    dayBookRoomBtn: '+ Забронировать зал',
    noBookingsTodayAvailable: 'Сегодня нет броней — свободно',

    // AdminDashboard
    adminDashboardTitle: 'Панель администратора (Admin Dashboard)',
    totalBookingsStat: 'Всего бронирований',
    totalHoursStat: 'Часов использования',
    roomColumn: 'Зал',
    dateColumn: 'Дата/Время',
    statusColumn: 'Статус',
    actionColumn: 'Действие',
    exportExcel: 'Export Excel',
    exportPdf: 'Export PDF',
    adminBackOfficeBadge: 'Admin Back-Office',
    adminFullPrivilegesDesc: 'Полные права администратора: просмотр, редактирование, удаление бронирований, аналитика и экспорт отчётов.',
    confirmedCountLabel: '{count} шт.',
    cancellationRateWithCount: 'Процент отмен ({count} шт.)',
    hoursPerRoomChartTitle: 'Часы использования по залам',
    hoursSeriesName: 'Часы использования',
    deptUsageChartTitle: 'Распределение бронирований по отделам',
    masterLogsTitle: 'Полный журнал бронирований',
    masterLogsDesc: 'Поиск, фильтрация, редактирование и удаление любых бронирований',
    searchPlaceholderAdmin: 'Поиск по теме, имени, email, отделу...',
    allRoomsFilterOption: 'Все залы',
    allStatusFilterOption: 'Все статусы',
    confirmedFilterOption: 'Подтверждено',
    cancelledFilterOption: 'Отменено',
    floorShort: '{floor} этаж',
    statusConfirmedPill: 'Подтверждено',
    statusCancelledPill: 'Отменено',
    editActionTitle: 'Редактировать (Admin)',
    deleteActionTitle: 'Удалить безвозвратно (Admin)',
    noResultsFound: 'Нет бронирований, соответствующих условиям поиска',
    deleteConfirmTitle: 'Удалить бронирование безвозвратно?',
    deleteConfirmDesc: 'Вы собираетесь удалить "{title}" пользователя {name}',
    deleteConfirmNotice: 'Удаление администратором сразу удаляет запись из базы данных и уведомляет пользователя по email.',
    deleteConfirmBtn: 'Удалить сейчас',
    hoursUnit: 'ч.',
    itemsUnit: 'шт.',

    // GoogleAuthModal
    ssoTitle: 'Вход через Google Аккаунт',
    ssoDesc: 'Подключите ваш аккаунт Google для автоматической синхронизации с Google Календарём и отправки e-mail приглашений.',
    ssoReconnectTitle: 'Переподключите Google Calendar',
    ssoReconnectDesc: 'Срок подключения к Google Calendar истёк. Нажмите кнопку ниже, чтобы переподключиться (отдел выбирать заново не нужно).',
    ssoConnectedTitle: 'Google Calendar',
    ssoConnectedDesc: 'Ваш аккаунт Google уже подключён.',
    loginGoogleBtn: 'Войти через Google',
    reconnectGoogleBtn: 'Переподключить Google Calendar',
    googleCalendarConnectedStatus: 'Google Calendar подключён',
    googleCalendarConnectedDetail: 'Ваши бронирования автоматически синхронизируются с Google Calendar — повторный вход не требуется.',
    connectingLabel: 'Подключение...',
    departmentLabel: 'Отдел',
    errorGoogleGeneric: 'Не удалось войти через Google: {msg}',
    ssoFooterAuth: 'Self-hosted PocketBase (Auth и база данных)',
    adminEmailLabel: 'Admin',

    // EmailDrawer
    emailDrawerSubtitle: 'Автоматические уведомления о бронированиях',
    noEmails: 'У вас пока нет уведомлений',
    noEmailsDesc: 'Уведомления появятся здесь после бронирования или отмены зала',
    markAllRead: 'Прочитать все',
    toLabel: 'Кому',
    fromSystemLabel: 'От: система уведомлений Villa Carte Group',
    clearBtn: 'Очистить',
    adminCopyNotice: 'Копия письма отправляется администратору {email}',

    // App-level toasts & misc
    bookingCreateFailedToast: 'Не удалось сохранить бронирование. Попробуйте снова.',
    bookingRaceConditionToast: 'Кто-то другой забронировал этот зал на то же время чуть раньше вас. Выберите другое время или зал.',
    bookingCreatedToast: 'Бронирование "{title}" успешно создано!',
    bookingCreatedGCalToast: 'Бронирование создано и синхронизировано с Google Calendar!',
    bookingUpdatedToast: 'Информация о бронировании обновлена',
    bookingCancelledToast: 'Бронирование "{title}" отменено',
    bookingDeletedToast: 'Бронирование удалено из системы',
    notificationsMarkedReadToast: 'Все уведомления отмечены как прочитанные',
    notificationsClearedToast: 'Список уведомлений очищен',
    notificationsActionFailedToast: 'Не удалось обновить некоторые уведомления. Попробуйте снова.',
    emailNotificationFailedToast: 'Не удалось отправить email-уведомление. Попробуйте снова.',
    signedInAsToast: 'Вход выполнен как "{name}" ({email})',
    sessionExpiredToast: 'Срок сессии истёк. Пожалуйста, войдите снова.',
    googleAuthNotice: 'Пожалуйста, войдите через Google (кнопка справа вверху), чтобы отправлять реальные приглашения в Google Календарь и на Email.',
    googleCalendarSyncExpiredToast: 'Срок подключения к Google Calendar истёк. Пожалуйста, подключитесь заново, чтобы это бронирование появилось в календаре (само бронирование уже сохранено).',
    googleCalendarSyncFailedToast: 'Не удалось синхронизировать бронирование с Google Calendar (само бронирование уже сохранено).',
    googleCalendarDisconnectedWarning: 'Google Calendar не подключён или срок подключения истёк — это бронирование всё равно сохранится, но не появится в Google Calendar, пока вы не подключитесь заново.',
    viewDetailTitle: 'Детали бронирования',
    viewDetailIdLabel: 'ID',
    roomLabel: 'Зал',
    dateTimeLabel: 'Дата и время',
    additionalGuestsLabel: 'Дополнительные участники (Google Email)',
    syncedToGCalLabel: 'Синхронизировано с Google Calendar',
    openInGCalLabel: 'Открыть в Google Calendar ↗',
    closeBtn: 'Закрыть',
    legendStandard: 'Standard: бронирование обычного пользователя',
    legendAdmin: 'Admin: бронирование администратора',
    legendVacant: 'Vacant: зал свободен для брони',
    footerSummary: 'Сводка за текущий месяц для Villa Carte Group Workspace',
    mobileNavSchedule: 'График',
    mobileNavRooms: 'Обзор',
    mobileNavMyBookings: 'Мои брони',
    mobileNavHelpdesk: 'Заявки',
    mobileNavAdmin: 'Admin',

    // IT Helpdesk
    helpdeskNav: 'IT Helpdesk',
    helpdeskTitle: 'IT Helpdesk',
    helpdeskSubtitle: 'Сообщите о проблеме или запросите помощь у IT-отдела и отслеживайте статус',
    newTicketBtn: '+ Новая заявка',
    ticketStatusOpen: 'Открыта',
    ticketStatusInProgress: 'В работе',
    ticketStatusResolved: 'Решена',
    ticketStatusClosed: 'Закрыта',
    ticketCategoryHardware: 'Оборудование',
    ticketCategorySoftware: 'Программное обеспечение',
    ticketCategoryNetwork: 'Сеть',
    ticketCategoryAccount: 'Учётная запись',
    ticketCategoryOther: 'Другое',
    ticketPriorityLow: 'Низкий',
    ticketPriorityMedium: 'Средний',
    ticketPriorityHigh: 'Высокий',
    ticketPriorityUrgent: 'Срочно',
    noTicketsFound: 'Нет заявок в этой категории',
    ticketRequestedBy: 'Заявитель',
    ticketResolutionNotesLabel: 'Заметки по решению',
    ticketResolvedByLabel: 'Решил(а)',
    ticketResolutionNotesPlaceholder: 'Заметки о том, как решена проблема (отправятся заявителю по email после отметки "Решена")',
    ticketAssignToMeBtn: 'Взять в работу',
    ticketMarkResolvedBtn: 'Отметить решённой',
    ticketMarkClosedBtn: 'Закрыть заявку',
    ticketReopenBtn: 'Открыть заново',
    newTicketModalTitle: 'Новая заявка',
    ticketTitleLabel: 'Тема',
    ticketTitlePlaceholder: 'напр. Компьютер не включается',
    ticketDescriptionLabel: 'Описание',
    ticketDescriptionPlaceholder: 'Опишите проблему подробно',
    ticketCategoryLabel: 'Категория',
    ticketPriorityLabel: 'Приоритет',
    submitTicketBtn: 'Отправить заявку',
    ticketTitleRequired: 'Пожалуйста, заполните тему и описание',
    ticketCreatedToast: 'Заявка отправлена.',
    ticketUpdatedToast: 'Заявка обновлена',
    ticketErrorToast: 'Что-то пошло не так. Попробуйте снова.',
  },
} as const;

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey, params?: Record<string, string | number>) => string;
}

const interpolate = (template: string, params?: Record<string, string | number>): string => {
  if (!params) return template;
  return Object.entries(params).reduce(
    (str, [k, v]) => str.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v)),
    template
  );
};

const detectDefaultLanguage = (): Language => {
  if (typeof navigator === 'undefined') return 'en';
  const candidates = navigator.languages && navigator.languages.length ? navigator.languages : [navigator.language];
  for (const raw of candidates) {
    const lower = (raw || '').toLowerCase();
    if (lower.startsWith('th')) return 'th';
    if (lower.startsWith('ru')) return 'ru';
    if (lower.startsWith('en')) return 'en';
  }
  return 'en';
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'th',
  setLanguage: () => {},
  t: (key, params) => interpolate(translations.th[key] || key, params),
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('vcg_app_lang');
    if (saved === 'th' || saved === 'en' || saved === 'ru') return saved;
    return detectDefaultLanguage();
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('vcg_app_lang', lang);
  };

  const t = (key: TranslationKey, params?: Record<string, string | number>): string => {
    const template = translations[language][key] || translations.en[key] || key;
    return interpolate(template, params);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
